[package]
name = "rust_file_encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
argon2 = "0.5.3"
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }
rand = "0.8.5"
